[build]
  command = "# no build command needed"
  publish = "public"

[functions]
  directory = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
